### PR TITLE
Fix: respect DisableEncoding for cached templates

### PR DESCRIPTION
**Pull request by DXInfinity**
DisableEncoding option was not applied to TemplatePage retrieved from cache.

### CODE REVIEW

**Comment by jzabroski** [comment]
@DXInfinity Can you add a test?  Thank you for your help, and apologies I didn't see this PR sooner.

**Comment by jzabroski** [comment]
@DXInfinity Just a nudge on adding a test here.  Thank you very much for the help with this PR.

**Comment by HamiltonManalo** [comment]
I jumped onto this branch to try and set up a couple of tests for it to get the PR merged through. It looks like the disable encoding option gets overwritten in the RazorEngineBuilder class. I'm examining the logic there to see if it can be an easy win.

**Comment by jzabroski** [comment]
Addressed in subsequent PR #373 which includes test

**Pull request closed without merging**
