### PR TITLE
Added support for .NET 6

### PR DESCRIPTION
**Pull request by leighmetzroth**
This is to fix issue #460 

Changes are as per @jacodv's branch leaving out some of the extraneous code and the test project. It also includes the workaround for ReSharper having issues with running the tests as I also run into it with the latest production version.

### CODE REVIEW

**Comment by jacodv** [comment]
@leighmetzroth - Well done and thank you!

**Comment by jzabroski** [comment]
The build workflow needs to be updated to support .net 6.

**Comment by jzabroski** [comment]
@leighmetzroth Can you please rebase the PR.  I tried to set-up automatic rebasing but since this is technically still @toddams repository, I cant add a personal access token to make the rebase work correctly.

**Comment by toddams** [comment]
@jzabroski I can add whatever is needed, just ask ;)

**Comment by leighmetzroth** [comment]
I've done the rebase and pushed it anyway

**Comment by jzabroski** [comment]
> I assume there is nothing else I need to do for now, you guys are sorting out the build workflow side of it?

I am trying to figure out exactly how GitHub Actions works.  I was assuming it would build any PR off the workflow specified in the main branch, but it seems to be taking it from the head commit of the PR instead.  This is something I never really noticed before

**Comment by leighmetzroth** [comment]
Would it be quicker and easier for me to close this PR and re-create?

**Comment by jzabroski** [comment]
Yes, that would probably be best.  Rebasing is the same thing.  But might be cleaner to re-do the PR.  Its a feature gap in how GitHub Actions and PRs work that there is no easy way to rebase (if there is, I dont know it).  GitHub lets you rebase the PR to the target branch, which is not what we want I think. See screenshot:

image

**Pull request closed without merging**
