### PR TITLE
Fixes #311 by taking the full namespace in the constructors that take…

### LINKED ISSUE #311: Incorrect template key when using constructor that takes assembly
When I'm using the constructor of `EmbeddedRazorProjectItem` it's setting the template key to assembly.GetName().Name, which will not include the namespace. So the embedded views aren't found, and there's no way to override it.

I believe the issue is in this line:
https://github.com/toddams/RazorLight/blob/744f545227083f17c63bcdef989bd5c2017ef53b/src/RazorLight/Razor/EmbeddedRazorProjectItem.cs#L23

There is also an issue that both the RootNamespace and Assembly properties that are exposed in the class have the setter exposed, but changing them won't do anything, the `fullTemplateKey` is only set in the constructor.

Suggested fixes:
1. Fix the constructor that takes an assembly so the full namespace is included, or require the root namespace to be specified (and overriding the full key)
2. Either remove the settings on the properties, or implement it properly so setting them will change the `fullTemplateKey`.

### PR DESCRIPTION
**Pull request by HakanL**
… an Assembly as the Assembly name isn't always the same as the namespace (it was the same in the unit tests that's why it worked there).

This change requires that projects that has the same namespace as the project name has to have the full namespace passed into the root namespace, I have updated the affected unit tests.

### CODE REVIEW

**Comment by jzabroski** [comment]
@HakanL I formatted the repository to follow the .editorconfig file. If you're using VSCode or Visual Studio 2017 or later, it should just pick up this config file and format correctly as you type unless you have some plug-ins that don't respect https://editorconfig.org/ conventions

**Comment by HakanL** [comment]
Should be good now, please confirm.

**Comment by harmandeol** [comment]
any plans to merge this ?

**Comment by jzabroski** [comment]
@HakanL Just published.  Should show up in nuget.org within the hour.  Thanks for your help.  Finally catching up from COVID-19 disaster planning prep.

**Comment by HakanL** [comment]
Awesome, thank you!

**Pull request merged**
