### PR TITLE
An example if how to use Verify

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by jzabroski** [comment]
@SimonCropp Why did you close it?  I wanted to use it, just been a bit behind with COVID-19.

**Comment by SimonCropp** [comment]
sorry. want me to resubmit?

**Comment by jzabroski** [comment]
Yes please.  Decent chance I may get to it on my vacation, although I did promise my wife I would step away from the computer most of my week off.

**Comment by SimonCropp** [comment]
should i base it on master?

**Comment by jzabroski** [comment]
Yes

**Pull request closed without merging**
