### PR TITLE
Enable TemplateTargetExtension

### LINKED ISSUE #236: The document type '' does not support the extension 'ITemplateTargetExtension'.
**Describe the bug**
Attempting to use Templated Razor Delegates produces the following error message:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Failed to generate Razor template. See "Diagnostics" property for more details
- The document type '' does not support the extension 'ITemplateTargetExtension'.
```

**To Reproduce**

```c#
@{
  Func<dynamic, object> b = @<strong>@item</strong>;
}
<span>This sentence is @b("In Bold").</span>
```

**Expected behavior**
Not crashing.

**Information (please complete the following information):**
 - OS: Windows 10
 - Platform .NET Core 2.1
 - RazorLight version 2.0-beta1

### PR DESCRIPTION
**Pull request by lars-nielsen**
Fixes #236

### CODE REVIEW

**Comment by toddams** [comment]
We use tabs for code formatting

**Comment by lars-nielsen** [comment]
I'll amend and commit an .editorconfig file along

**Comment by lars-nielsen** [comment]
@toddams updated, 

Btw. I saw a lot of mixed tab and spaces indentation, ive purposely not fixed that to keep the PR as small as possible

**Comment by toddams** [comment]
Great job man :) I appreciate that. Merging

**Comment by lars-nielsen** [comment]
You're welcome.

I'll create a pull request more in about ½ an hour to support conditional html attributes

<span attr="@if (Model) {}"></span>

**Pull request merged**
