### PR TITLE
avoid locking threads on compile

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by toddams** [comment]
Thank you for your contribution. 
Can you please provide some explanations to your further MR, like what this change is introduced and what issue it resolves. I am also curious about this one, why SemaphoreSlim instead of lock?

**Comment by SimonCropp** [comment]
SemaphoreSlim allows async waiting. which doesnt block a thread

**Comment by jzabroski** [comment]
@toddams Is it causing any problems? It seems useful to me to be able to avoid blocking congestion? Granted, I don't have any uses with millions of requests a second that might be worth writing a benchmark test for.

**Comment by SimonCropp** [comment]
@jzabroski i didnt do this for perf reasons. but to remove the `.GetAwaiter().GetResult();` which is a common cause of deadlocks

**Comment by jzabroski** [comment]
@SimonCropp That is what I am referring to.  My understanding is the deadlock only triggers when you exhaust all threads and the threads can't finish because the "buffer" in this case is the thread pool size.  Am I wrong?  Thank you.

**Comment by jzabroski** [comment]
Currently, our RaceCondition Tests in the build run in ~20 seconds but I think we only create 1,000 tasks, which would not stress the thread pool I believe.  I wonder if the test (or another test) should call [ThreadPool.GetMaxThreads](https://docs.microsoft.com/en-us/dotnet/api/system.threading.threadpool.getmaxthreads) and create a scenario where we test the number of concurrent tasks > max threads.

**Pull request merged**
