### PR TITLE
upgrade to .netcore 3.0

### PR DESCRIPTION
**Pull request by zhongzf**

### CODE REVIEW

**Comment by jzabroski** [comment]
I'll review this tonight or tomorrow.

**Comment by Goxiaoy** [comment]
Any update?

**Comment by jzabroski** [comment]
@Goxiaoy I'm wrapping up a project at work where a mistake could cost my clients millions of dollars in an instant.  Once that is wrapped up, I will focus on this.  Have to pay the bills and build my brand, first.

**Comment by Goxiaoy** [comment]
@jzabroski Thank you so much and wish you good luck.

**Comment by jzabroski** [comment]
Started looking at this tonight. Just installed  .net core 3 today. I think
things are a bit whack in that some open PR are target the dev-2.0 branch

**Comment by gjunge** [comment]
Would be great if we can multi target both netstandard2.0 and netcore 3.0

**Comment by jzabroski** [comment]
@gjunge 's pr is better.  Closing this one.

**Pull request closed without merging**
