### PR TITLE
Update Embedded Resource Docs to be more explicit

### PR DESCRIPTION
**Pull request by mwasson74**
#472

### CODE REVIEW

**Comment by mwasson74** [comment]
Do I also need to update README.source.md? I wasn't sure what or how that file is used...

**Comment by jzabroski** [comment]
Yes.  README.source.md is the actual readme.  We use a tool by Simon Cropp that allows dynamically including code snippets into the readme file so that the code snippets can be type checked by C# compiler.

**Comment by mwasson74** [comment]
@jzabroski I reverted the previous changes and hopefully made them the correct way this time. Please let me know if there's anything I need to fix!!

**Comment by jzabroski** [comment]
Almost perfect.  If you build the code it will update the `README.md`, then you can check in the source, snippets cs file, and the readme.md in one commit.  Do you want to squash your commits and submit a new PR so its clean?

**Comment by jzabroski** [comment]
@mwasson74 I'll did it for you.

**Comment by mwasson74** [comment]
@jzabroski thanks! I tried, squashing via interactive rebase but that must not have been what you were referring to...?

**Comment by jzabroski** [comment]
To be honest, I didnt know GitHub PRs supported "squash and merge" . I normally just click Merge pull request.  I should probably update my best practices to reduce a lot of noise.

**Comment by mwasson74** [comment]
Ha!! The company I work for uses an on-prem instance of Azure DevOps with Git as a source control. We have a policy setup on all of our repos that force a squash commit when merging 👌

**Pull request merged**
