### PR TITLE
Fix based on @glikoz solution

### LINKED ISSUE #147: Could we use this library with .Net 4.6.1 in the future?
Will this library compatible with .Net Framework 4.6.1 ?
It seems  Full .Net Supported version was updated a year ago.
https://github.com/toddams/RazorLight/tree/full-net-support

Thanks.

### PR DESCRIPTION
**Pull request by colinbull**
Fixes #147 and #133 I have been successfully using this on .net 471, and net 461. 

This is a direct copy of @glikoz s original solution.

### CODE REVIEW

**Comment by colinbull** [comment]
Build failure looks like existing issues with the Sandbox project, referencing the incorrect framework.

**Comment by toddams** [comment]
Thank you for your work 👍

**Comment by bottomup** [comment]
Great work guys! Can we expect an updated NuGet package?

**Comment by toddams** [comment]
I'm preparing html helpers, will release with that

**Comment by rendmath** [comment]
This is a blocking issue for us. Any chance we could get a new NuGet package, with or without the HTML helpers?

**Comment by chrismasters** [comment]
Possible to publish this to pre-release nuget feed?

**Comment by alexandre-spieser** [comment]
yes please, can you publish a pre-release, I am facing the same issue on a 4.7.1 project.

**Comment by churtado** [comment]
Having the same issue as well, a pre-release would be good!

**Comment by Nekromancer** [comment]
Same here

**Comment by WadeTheFade** [comment]
I just ran into this issue as well. 4.6.1 .net standard 2.0 console application.

**Comment by gtaylor44** [comment]
This is working but it's a pain to do an adhoc build and ensure all the dependencies are correctly configured:

    <PackageReference Include="Microsoft.CodeAnalysis.Razor" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Html.Abstractions" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.Extensions" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Language" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Runtime" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Physical" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="2.1.0" />
    <PackageReference Include="System.Buffers" Version="4.5.0" />

A release would be greatly appreciated. 

My build was done from master.

**Pull request merged**
