### PR TITLE
Abstracted the EngineFactory and the RazorLightEngine to use interfac…

### PR DESCRIPTION
**Pull request by jholovacs**
…es so they could be easily mocked.  This allows the EngineFactory to be injected as a dependency, while still allowing code to be tested in isolation.

### CODE REVIEW

**Comment by jholovacs** [comment]
It looks like the Travis CI server is not properly configured.

**Comment by toddams** [comment]
Hi @jholovacs 
Thank you for your contribution! Travis do used to work, but something broke up eventually.
I will take a look at it asap.

**Comment by jholovacs** [comment]
Thanks!

**Comment by jholovacs** [comment]
Why was this closed instead of merged?

**Comment by toddams** [comment]
We discussed these changes and came to a conclusion that these abstraction is kinda pointless.

**Dependency Injection**
If you want to use dependency injection - RazorLight already implements IRazorLight interface. You can use RazorLight.MVC that enables you to add RazorLight to default ASP.NET MVC Core IServiceProvider and retreive it from your controllers. Moreover it also allows you to use @inject directive to inject services directly to your views.
If you don't use ASP.NET MVC Core - you can register IRazorLight service with a factory delegate

````CSharp
    container.Register(typeof(IRazorLightEngine), () => EngineFactory.CreatePhysical("Your path"));
````

**Testing and mocking:**
You extracted an interface from TemplatePage, but it contains important logic that predefines this template behavior and must not be changed. In RazorLight scenario each page must inherit TemplatePage abstract class. And abstract classes can be mocked as well, and we do it in our RazorLight.Tests project.

So at the end I see this as abstraction for the sake of abstraction, that's why pull request was closed.

**Comment by jholovacs** [comment]
Well, FWIW, I think you're 100% wrong.  Mocking an abstract, especially one
with significant logic inside it, violates one of the primary tenets of
unit testing, namely, isolating the code you want to test.  If you want to
test the code using the template page, but don't want to actually test the
text generation, you now have a problem when it fails.  How do you know
it's the code you wrote that did not behave as expected, rather than this
dependency?  You can't, because they are tightly coupled.

I'm disappointed in this decision, and I'll look for a different template
engine.

**Pull request closed without merging**
